language: scala
scala: 2.12.10
jdk: openjdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "luh8iE4Zn3OtesQ3wCTICcaH6UI7bZwK8Z/vvLuN0Ok8XidbRwyBVXIMwipjSHJ9K9hYR1P/e80PiNbjzJd4kRGhLqQ1z7Aq0oTH6pYQvB7/oLP1S4GAoIv4Ao/LKFVJq+4Q2up/PKqopzsyHf/viHMxtXXxhWh9ZSBSmP+NE5xL3qbV0T90S4B1p1g7rakzXQVb2lUEHA32RBlhdAo2Yx6nMmKW612tVSiErRA6vYbJoMFx+XLb6tZcfSqReL0SNQBTNxl6c4I5o7FNu63Vl72zM2bCHKZiVTzc4UAnZm+AdV4OsmztQ5ZLkSZ/OYo7kk+znI5DVaVCF7Fwl2Nx9GTE25Dy5Efc7izW3jOcaQnqNa0etkDNC787JHOscjGIRtQbgzmQMhK15R3k2xGTN/Xd6cjDfFwRGyDKWRl1nmkIjz/dXt3A8FTeI7nnv4cRWpGUpKeAxyCUIv+2uNBT0cDuHR9WGgznPmoITDP819aGn0hGkSxt7WEIFvXf8hZxR2qHkKL628Zzk+JPomhQVKRlctGhHYSZtsun6sKk6ucVQicZKY3FJY0KrsZI59txQ8RgUEUICN4hB9/EFdE9cOLDwmL05NZXNRlJACMUknkvmVyZPOVI7Q8SrVRBLnHADhtgN0VFe6ji5S7iNif5wJA4RuZ16UBrN9l4zFG+5i8="
    # GITHUB_TOKEN
    - secure: "Na1fE8MHkIXdDobgn+3bIS6ME1oKbKOJSBIe2ncQpBOj6MGWpZANNxt1LDLnHpsRHJK5jzNNUQvyXLuCb3gfmJxPVws7albr14LbOkKgIKAs2zwvYAmnky4Bf1KowV9Q/Jy6+wmGcn1EHTbCPcBZgQyIjZ98zb3AWhv+lDTjN9FeIa89zVaseRtRNuXKyhQ4bHg5t9x6lvLSoKJf916N0OtT7LHdzvfRiYknWF1hU5IlidkM6kG1wyqu7UxGyxF7ftYHEs8oBavBHheO4zYN/5eF2FYfA4NgnAVVB3ebMkmFKm8zipD4OWGlXKShNB7UOWTurjotbN3pnK5D2/y6mBNaXqa5d0M39UdMgEQDxrqtMChrcu5xNCe5Hy8Qn3PNN+K/gGMtJrjQqAFXXvp5FawcSirDxRXE76ZK+UFheQgL3zFpSyZrEjNO8zkfXWFTftZZRjW116IbdOb8awGnM5ag3tO53ip/RYAI9ZCIECAH9u4RrDgc+f0+yAp2lw0/SHFUzAiZ5DHGcO4RpkuqOcdUf2i+DvrdLSg5NmSJQtKPBfCwq1ITZg+dBSlE8HML3sA74t2PG3v9t8AfZO9cKIwZv6OT37TIq22Q6bqDiitrtnvFIrm1vvpTygqymGV7iIT2B39FCaCJwjx6sYmavpYIenOFSQIGn9SEej31Rrw="
    # GITHUB_ACCESS_TOKEN
    - secure: "M9JY0DmRngRBf/NftZzzYRgB/qmJdTuTi9QxkTfPE6vaSZiAZLDxO0YJ6swn1sAHaJcecRIu6BR3XMtWMI3mkoalXkNf/ulg29XGdPbpPnmCKAjfmpAJo0o2UmUD9drQPo/qFWAa4WGu2Y4O2Mg85C5DGwn4z8yNwgermx9TOv85SN+u2I9lL9rwRf4Wiymz5+xGjutMpRCtqwobSmmxeAQjqzL8Wb0L1aCeh6iah64Q9se04bS69XglLXLGFyUoU/x9Eqq5d1KTQ5+Rk4DAT04NiZy2uJOv5jEuECO+jCet7GvlB1OcxXXKriifSmCVXbPerV1X+Uw4SHh4z6PlPko6UYbou5gnZaTbD9ZF3QyogA7dHR3sb83uLglONLD9CZZ87aJKwAdUicPyp1qkawatny2qD5YPa6dt9FMwJSPJhwF9O11FIJioMblxmM5/nyiDJXvkXUmgke+IJZ1VwHFcVGxf0Cqx6BVsw2A1/fAlMHfZ1bretQyQSHgYvYwg6+fhepWo4RQrCnYhJXKbCR3pDcZ6nYF8ytRm83WXGbjR3ufXBj5Qb0CiAsIdb1FjVDEoNytfrBBQ95poS778ZEKlxWTc0fpSYoA9YgrATTKfoZW+17r59kbQy3jWFz48gAIk6P5UaVtkKfaa0r1z3/1yuquRZfEzzWnMf3gUZTM="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "UMbyX3/fI5H49EShjglPyS2oftBeS/iPDypZeZz18ktS8WXFaZM7g/vD1SS/w1gGdwS/lmNJ2Fyjm8B4XHS9GA0Qf+Una7n/C+hUmmSQGZ6MlIvCVGVr1YoYJnRx+03SNSnR11miDvs/6B7AqzNfEUveoVo90qjfcXtIGnPUwtLscfCOuSYkuKpT3hBo4VbWErG357U23o0tKpWL1x97+SRzj97YchPheyJcRRXwhsVnzmGzKpdoX6LrkFXNdCql/QH8aP5YIJOq9v1uh14HDxFrS0uDRB/h7mq3HQbzY3tLjEQJaSL/b5lr6v63V2f9Mckevuni5ynbYSBRcXU/Pk43HNIhIJt856pjkt3OYttMLuXrmjo3SsjxDUBDdoLqJKVVEoNTl9WNp/aKEPHQhwbDgB23zn212VjX1Nt5pWsQ5rs7md8ZYFZu4TJDoxUV2fE+mFHvUD/Uron6+34lKF5hyqyFFQ8zaYy1t5Jn5YLrvkd+IicXJ2ddDXfJlxJQA9/IMSdp3Mx1VZyRj0pq6TAd1apkSPOql+C3RE9xcZmK6qJpbra5lhUJE2sWeldxOPZJ0gWlEKahiCAdhWkOAbhv3HDZHB4zjt1ycP1v5nV1otqrX97LI6AVB36L8ZOcQ2qkt+BNZLMJQY5crslfKyMeUHFmPN6dlgI/pEC/gCE="
  matrix:
    - POSTGRES_MAJOR=9
    - POSTGRES_MAJOR=10
    - POSTGRES_MAJOR=11

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
  - set -e
  - docker-compose up -d postgres${POSTGRES_MAJOR}
  - $SBT ++$TRAVIS_SCALA_VERSION test

jobs:
  include:
    - stage: publish
      env: POSTGRES_MAJOR=9
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-postgres'

      git:
        depth: false

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
